# Application port
server:
  port: 8081

# Default connection pool
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    # PostgreSQL
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres

  # Default Schema
  flyway:
    schemas: products
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    properties:
      hibernate:
        default_schema: products
